library(dplyr)
caschool <- read_excel("Desktop/files/College/3rdYear/ECON21020/Econ-21020/caschool.xlsx")
caschool$income <- caschool$avginc*1000
mean(caschool$avginc)
sd(caschool$avginc)
mean(caschool$income)
sd(caschool$income)
mean(caschool$math_scr)
less20 <- caschool %>% filter(str<=20)
count(less20)/count(caschool)
mean(less20$math_scr)
greater20 <- caschool %>% filter(str>20)
count(greater20)/count(caschool)
mean(greater20$math_scr)
se1 <- sd(less20$math_scr) / count(less20)
se2 <- sd(greater20$math_scr) / count(greater20)
se <- sqrt(se1+se2)
sd(less20$math_scr)
t <- (mean(less20$math_scr)-mean(greater20$math_scr))/se
t
cov(caschool$avginc, caschool$math_scr)
cov(caschool$income, caschool$math_scr)
cor(caschool$avginc, caschool$math_scr)
cor(caschool$income, caschool$math_scr)
